// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhrXYmCZ2PvQrhiE3PXlA1rakjIcBptw4',
    appId: '1:382540859064:web:1fa736883649948c9ed64d',
    messagingSenderId: '382540859064',
    projectId: 'my-app-1b104',
    authDomain: 'my-app-1b104.firebaseapp.com',
    storageBucket: 'my-app-1b104.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi9m0or2ENmMS5A1CRJ-mzmZsaQ3HofQg',
    appId: '1:382540859064:android:7bd680da68775b379ed64d',
    messagingSenderId: '382540859064',
    projectId: 'my-app-1b104',
    storageBucket: 'my-app-1b104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgn-DRFRD457qqLfwXYwxsXR2KEgXoBK0',
    appId: '1:382540859064:ios:c08b6691ffecbbdd9ed64d',
    messagingSenderId: '382540859064',
    projectId: 'my-app-1b104',
    storageBucket: 'my-app-1b104.appspot.com',
    iosClientId: '382540859064-rbhlk7kc3h8pkch5n4rob5bb4pd5ratu.apps.googleusercontent.com',
    iosBundleId: 'com.myapp.myApp',
  );
}
